services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nations-flow_web
    command: ["./wait-for-database.sh", "gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120", "--workers", "3", "--worker-class", "sync", "--keep-alive", "5", "--max-requests", "1000", "--max-requests-jitter", "100"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - nations-flow_net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nations-flow.rule=Host(`nationsflow.com.br`)"
      - "traefik.http.routers.nations-flow.entrypoints=websecure"
      - "traefik.http.routers.nations-flow.tls.certresolver=myresolver"
      - "traefik.http.services.nations-flow.loadbalancer.server.port=8000"
      - "traefik.http.services.nations-flow.loadbalancer.server.scheme=http"
    restart: always

  db:
    image: postgres:15
    container_name: nations-flow_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - nations-flow_net
    restart: always

networks:
  nations-flow_net:
    driver: bridge
  proxy:
    external: true
