services:
  db:
    image: postgres:15
    container_name: postgres-nations
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nations
      - POSTGRES_PASSWORD=91Jgy0q8a5BnV
      - POSTGRES_DB=nationsflow
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-nations
    command: >
      sh -c "python manage.py wait_for_database &&
             python manage.py makemigrations && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/nations-flow/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: