site_name: Nations Flow Documentation
site_description: Sistema de gestão financeira para igrejas
site_author: Nations Flow Team
repo_url: https://github.com/vwtechdev/nations-flow
repo_name: Nations Flow

theme:
  name: material
  language: pt
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Introdução:
    - Visão Geral: overview.md
    - Instalação: installation.md
    - Configuração: configuration.md
  - Desenvolvimento:
    - Docker: docker.md
    - Estrutura do Projeto: project-structure.md
    - API e Modelos: api-models.md
  - Funcionalidades:
    - Dashboard: dashboard.md
    - Gestão de Usuários: users.md
    - Gestão de Igrejas: churches.md
    - Gestão de Transações: transactions.md
    - Relatórios: reports.md
    - Sidebar Minimizada: sidebar-minimization.md
  - Administração:
    - Backup e Restauração: backup-restore.md
    - Troubleshooting: troubleshooting.md
  - Contribuição:
    - Guia de Contribuição: contributing.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
