# Generated by Django 5.2.4 on 2025-11-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='repeat',
            field=models.BooleanField(default=True, verbose_name='Repetir Notificação'),
        ),
        migrations.AddField(
            model_name='notification',
            name='repeat_frequency',
            field=models.CharField(choices=[('none', 'Não repetir'), ('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente'), ('annually', 'Anualmente')], default='none', max_length=10, verbose_name='Frequência de Repetição'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('treasurer', 'Tesoureiro'), ('supervisor', 'Supervisor')], default='treasurer', max_length=20, verbose_name='Função'),
        ),
    ]
