# Generated by Django 5.2.4 on 2025-08-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_church_from_user'),
    ]

    operations = [
        # Simplificar o modelo Field - remover campos desnecessários
        migrations.RemoveField(
            model_name='field',
            name='churches',
        ),
        migrations.RemoveField(
            model_name='field',
            name='user',
        ),
        migrations.RemoveField(
            model_name='field',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='field',
            name='updated_at',
        ),
        
        # Adicionar campo field em Church
        migrations.AddField(
            model_name='church',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.field', verbose_name='Campo'),
            preserve_default=False,
        ),
        
        # Adicionar campo field em User
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.field', verbose_name='Campo'),
        ),
        
        # Renomear description para desc em Transaction
        migrations.RenameField(
            model_name='transaction',
            old_name='description',
            new_name='desc',
        ),
        
        # Renomear updated_at para last_update em Transaction
        migrations.RenameField(
            model_name='transaction',
            old_name='updated_at',
            new_name='last_update',
        ),
        
        # Adicionar campo church em Transaction
        migrations.AddField(
            model_name='transaction',
            name='church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.church', verbose_name='Igreja'),
            preserve_default=False,
        ),
    ]
