# Generated by Django 5.2.4 on 2025-08-05 00:42

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apply_new_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(default=timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(default=timezone.now, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
