# Generated by Django 5.2.4 on 2026-07-30 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_accesslog_options_remove_accesslog_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='churches/%Y/%m/%d/', verbose_name='Contrato da Igreja'),
        ),
        migrations.AddField(
            model_name='shepherd',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='shepherds/%Y/%m/%d/', verbose_name='Contrato do Pastor'),
        ),
        migrations.CreateModel(
            name='ShepherdHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Registro Ativo')),
                ('start_date', models.DateField(verbose_name='Data Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.church', verbose_name='Igreja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('shepherd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shepherd', verbose_name='Pastor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Histórico de Pastor',
                'verbose_name_plural': 'Histórico de Pastores',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
    ]
