# Generated by Django 5.2.4 on 2025-08-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_timestamps_to_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=False, verbose_name='Senha Alterada'),
        ),
    ]
