# Generated by Django 5.2.4 on 2026-08-04 21:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shepherd_history_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=app.models.church_contract_path, verbose_name='Contrato da Igreja'),
        ),
        migrations.AlterField(
            model_name='shepherd',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=app.models.shepherd_contract_path, verbose_name='Contrato do Pastor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to=app.models.transaction_proof_path, verbose_name='Comprovante'),
        ),
    ]
