# Generated by Django 5.2.4 on 2026-08-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_accesslog_options_remove_accesslog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Administrador Principal'),
        ),
    ]
