name: Deploy VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}

          script: |
            set -e

            cd ~/projects/nations-flow

            echo "Atualizando repositório..."
            git pull origin main

            echo "Aplicando migrations..."
            docker compose run --rm web python manage.py migrate --noinput

            echo "Subindo nova versão..."
            docker compose up -d --build --remove-orphans

            echo "Limpando imagens antigas..."
            docker image prune -f

            echo "Deploy finalizado!"
